version: "3.8"
services:
  product_management_service:
    build: ./product_management_service
    ports:
      - "5001:5001"

  order_management_service:
    build: ./order_management_service
    ports:
      - "5002:5002"

  stock_management_service:
    build: ./stock_management_service
    ports:
      - "5003:5003"

  api_gateway:
    image: nginx
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
